### ISSUE TITLE
Não atualização de status do pedido

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-paypal#25]
O pedido https://app.e-com.plus/#/resources/orders/60427b476d50911b60554a21 da loja ID 1035 está em análise, enquanto no paypal consta como pago. Pelo que verifiquei via API a aprovação foi 2 minutos após o pedido em análise. 
No link .../paypal.error e .../paypal.out não constam nada para isso

**Comment by leomp12** [comment]
Não tem erro nenhum do nosso lado, só recebemos o webhook do PayPal com atraso (4 horas depois da alteração feita manualmente).

No log só tem um registro:

```console
PayPal event type PAYMENT.SALE.COMPLETED for 02G10993C1070442C
```

No pedido essa notificação foi tratada, mas foi após a alteração manual para status pago:

![Screenshot_2021-03-06 E-Com Plus Dashboard App](https://user-images.githubusercontent.com/10326572/110210423-6f14c080-7e70-11eb-8991-b063d731c6ba.png)
