### ISSUE TITLE
No checkout não está mostrando parcelamento sem juros

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-paypal#26]
Todas formas de pagamento mostram detalhes de juros, no paypal não está mostrando.
![image](https://user-images.githubusercontent.com/35343551/124323082-0d7f0d00-db57-11eb-93a2-3d42debd3b4b.png)

**Comment by leomp12** [comment]
Mas tá configurado no app a opção de parcelamento? Isso aí é quase que só um bypass da configuração.
