### ISSUE TITLE
Handle funding failures

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-paypal#27]
When possible, we can handle funding failures to allow customer to use another funding to pay their order.

https://developer.paypal.com/docs/platforms/checkout/add-capabilities/handle-funding-failures/

**Comment by leomp12** [comment]
Você sabe que isso não funciona em PayPal Plus né? Você está apontando a referência do PayPal global, seria bem legal se aqui pro Brasil desse pra usar ela também, mas não é o caso...
